import json,csv,hashlib
from pathlib import Path
ROOT=Path('D:/zx/test');Q=ROOT/'project/qa'
def reg(x,y):return [(x*1024/17683-327)*.0524,(540-y*789/13632)*.0531]
pts={'west_concrete_north_outer':[13895,7175],'west_concrete_north_inner':[13962,7271], 'west_concrete_south_outer':[13905,10226],'west_concrete_south_inner':[13973,10131], 'east_concrete_south_outer':[15470,10224],'east_concrete_south_inner':[15402,10128], 'south_west_stone_inward_face':[14024,10230],'south_east_stone_inward_face':[15352,10230], 'south_dimension_left_witness':[14028,11254],'south_dimension_right_witness':[15359,11254], 'NW_stone_outer_corner':[13380,7080],'NW_stone_inward_end':[14010,7271],'SW_stone_outer_corner':[13310,10131],'SW_stone_leg_end':[13310,10680],'SE_stone_outer_corner':[15998,10128]}
rows=[]
for name,px in pts.items():rows.append({'landmark':name,'upright_native_px':px,'normalized_1024_789_px':[px[0]*1024/17683,px[1]*789/13632],'world_xy_m':reg(*px),'evidence':'C author trace from B viewed HABS sheet; not surveyed precision','native_trace_uncertainty_px':5,'world_registration_uncertainty_m':.05})
meta={'original_tiff':'research/references/architecture/main-04-original.tif','original_sha256':'3db8199eeb84cd4226cfbae2ea9192880454c1012afa6e33bf84bae6449d8d56','full_tiff_tool_view':'FAILED_INVALID_BASE64','actual_inspection':'Viewed 4 lossless native crops produced by source TIFF read and exact CW90; supplied overview PNG also viewed. No retouching or image invention.', 'registration':'upright=(17682-raw_y,raw_x); u=ux*1024/17683,v=uy*789/13632; X=(u-327)*.0524,Y=(540-v)*.0531; drawing axes, not geographic north','landmarks':rows,'nominal_source_constraint':{'identity':'Opposing inward vertical end faces of SOUTH stone returns','printed':'13 ft 3 in','nominal_m':4.0386,'center_C_m':27.44974,'proposed_faces_m':[25.43044,29.46904],'not_identity':['deck width','thin concrete wall spacing','central rectangle','four corner blocks']},'unknown':['central rectangle and 4 blocks','sub-deck structural system','actual foundation bottoms','photo surveyed material dimensions'],'rendered':False}
(Q/'bridge10-source-identity.json').write_text(json.dumps(meta,indent=2),encoding='utf8')
photos=json.loads((Q/'bridge-source10-download.json').read_text()); viewed=[]
obs=['Longitudinal bridge view: continuous pale concrete parapets, rounded visible terminal profile, layered stone bank returns. Central rough surface differs from flanking flags; historical composition not dated independently.','Transverse view: single uninterrupted pale concrete wall with low layered stone return at end; photo does not measure thickness or foundation.','House-side view: two pale continuous parapets, front face extends below paving, substantial layered stone bank faces. Human scale supports only C height estimate; hidden foundation unknown.']
header=next(csv.reader((ROOT/'project/reference_manifest.csv').open(encoding='utf-8-sig')))
with (Q/'bridge10-reference-manifest-append.csv').open('w',encoding='utf8',newline='') as f:
 w=csv.DictWriter(f,fieldnames=header);w.writeheader()
 for p,ob in zip(photos,obs):
  assert hashlib.sha256((Q/p['path']).read_bytes()).hexdigest()==p['sha256']
  record={**p,'actual_view':'VIEWED_BY_SITE_VISUAL','viewed_utc':'2026-09-20T17:42:00Z','observations':ob,'photo_evidence':'B direct photograph; C inferred construction dimensions','distribution':'REFERENCE_ONLY_EXCLUDE_PUBLIC_PACKAGE'};viewed.append(record)
  hyde=p['id']=='hyde-bridge'
  r={k:'' for k in header};r.update({'ref_id':'BRIDGE10_'+p['id'].upper().replace('-','_'),'title':'Fallingwater bridge construction reference '+p['id'],'institution':'Dan Hyde / Bucknell hosted personal page' if hyde else 'Columbia University MCAH','item_id':p['id'],'sheet_or_photo':'photograph','url':p['source_page'],'local_path':'project/qa/'+p['path'],'source_date':'2005-04-22' if hyde else 'UNKNOWN; filename contains 2001, not independently confirmed','accessed_date':'2026-09-21','view_direction':'house-side toward bridge' if hyde else ('longitudinal toward curving approach' if p['id']=='columbia-0' else 'transverse toward parapet'),'rooms':'SITE bridge','use':'construction reference only; concrete parapets and layered stone bank returns','evidence_level':'B','rights_note':'Copyright Daniel C. Hyde 2005; reference only; exclude public package; no texture reuse' if hyde else 'No redistributable license verified; reference only; exclude public package; no texture reuse','verification_status':'HASH_VERIFIED_VIEWED','source_url':p['url'],'sha256':p['sha256'],'bytes':p['bytes'],'hash_provenance':'Local SHA256 independently recomputed by bridge10 registration script','visual_status':'VIEWED_BY_SITE_VISUAL','status_provenance':'project/qa/bridge10-reference-viewed.json','parent_ref':'','asset_class':'REFERENCE_ONLY_EXCLUDE_PUBLIC_PACKAGE','local_path_check':'EXISTS_HASH_MATCH'});w.writerow(r)
(Q/'bridge10-reference-viewed.json').write_text(json.dumps(viewed,indent=2),encoding='utf8')
print(json.dumps(rows,indent=2))
