import json,hashlib
from pathlib import Path
R=Path('D:/zx/test/project');Q=R/'qa'
c=json.loads((Q/'bridge10-candidate-check.json').read_text());r=json.loads((Q/'bridge10-candidate-readback.json').read_text());w=json.loads((Q/'bridge10-water-spatial-mask.json').read_text())
lines=['# Bridge 10 handoff — isolated structural candidate','',
'Geometry/readback PASS; visual acceptance NOT_RUN; complete water QA NOT_PASSED. No production hook or original scene changed. No rendering was performed.','',
f"Candidate: `scene/Fallingwater_bridge_candidate10_meshclean.blend`\n\nSHA256 `{c['candidate_sha256']}`. Source full09 `{c['source_sha256']}`. Saved frame73; render comparisons must explicitly use frame48.",'',
'The 77 exact original stone-parapet objects were removed only in this candidate. Seven new objects provide two continuous .20m concrete parapets with rounded ends, four terrain-seated layered stone L returns, and a .123m west edge closure. The existing deck, flags, four deep abutments, both approaches and all other objects remain unchanged. The photos establish construction identity; positions/heights/thicknesses and foundation continuation remain C with uncertainties in `bridge10-source-design.md`. The central rectangle/four squares remain U, with no new obstacle.','',
f"Verification: {c['fingerprint']['retained_object_count']} retained object fingerprints identical; original material/light/camera/render/config globals identical; {len(c['protected_physics'])} core/shoulder/water evaluated physical hashes unchanged. All seven new evaluated meshes are closed and finite, with zero zero-area polygons or triangles. Fresh-process reopen reproduced the full scene fingerprint and new physical hashes.",'',
'Nine evaluated face-to-face horizontal rays through the SOUTH stone return ends measured **4.038599014m** against nominal **4.0386m (13 ft3 in)**. Both actual inward faces and their normals were validated, not inferred from object bounds. This is the nominal south return gap, not deck width. The retained walking route had11,554 checks and0new obstacles. All129 existing cameras retain their transforms; minimum distance to any new bridge mesh is4.8165m. Each of220 foundation perimeter samples sits20mm below the same frozen terrain.','',
'## Remaining water boundary','',
'Water-bank contact is expected. The specific unresolved issue is that the old continuous river still contains triangles inside the new CLOSED masonry volume. The spatial probe clips each water triangle against the actual sloping lower triangles of the L core and its top plane. It therefore excludes water below the foundation, rather than treating every XY overlap as a collision. Shallow stone face projections are included in the exact crossing-point BVH test but excluded from the core interior area.','',
'| Return | Actual intersection X | Y | Z | Upward water surface inside core |','|---|---:|---:|---:|---:|']
for t in w['targets']:
 if t['actual_intersection_aabb_xyz_pairs']:
  b=t['actual_intersection_aabb_xyz_pairs'];lines.append(f"| {t['bridge_object']} | {b[0]:.6f}…{b[1]:.6f} | {b[2]:.6f}…{b[3]:.6f} | {b[4]:.6f}…{b[5]:.6f} | {t['upward_water_inside_core_area_xy_m2']:.6f}m² |")
lines += ['', 'Both intersections are below the original deck bottom−.555m and paving+.012m, never through the road-height stone faces. The north returns have no intersection. These measurements do not prove how much is visible through water/refraction in a rendered view; root must inspect the images. Opaque masonry may hide internal water, but the triangles have not been physically trimmed at the new shore.','',
'`bridge10-water-spatial-mask.json` is the detailed trim evidence: actual intersection points, intersecting evaluated water-triangle IDs, clipped polygons, L-core rectangles and actual bottom-plane method. `bridge10-water-spatial-summary.json` is the short version. For the later water pass, retain the real L masonry and trim only the water portion INSIDE its evaluated volume, preserving the central stream and every elevation. Do not cut the entire AABB box or lower terrain/core. Both upper and lower river faces are present, so the combined projected area is not a unique surface area; use the upward-facing area column above. The old full river has409,192triangles and a very broad inheritedAABB; it is not a suitable global mask.','',
'## Root render pair','',
'Use the same temporary QA cameras for frozen09 and the mesh-clean candidate, frame48, unchanged exposure/material/light settings. These suggestions were ray-probed without creating cameras; no obstruction lies within .20m of either camera, and wall-target rays first hit the intended bridge components. They are authored QA views, not surveyed source cameras.','',
'| QA view | Camera XYZ | Target XYZ | Lens | Purpose |','|---|---|---|---|---|',
'| SOUTH_APPROACH | (27.45,−10.5,1.8) | (27.45,2.0,.25) |28mm| Both rounded parapets and south stone endpoints/13′3″ gap |',
'| HOUSE_SIDE | (18.0,1.0,3.8) | (27.45,1.5,−.25) |28mm| Continuous pale concrete elevation and tall stone bank faces, comparable to Hyde composition |','',
'Parent schedules CPU renders; this agent ran none. A front/side visual comparison remains necessary before structural appearance acceptance.','',
'## Helper and archives','',
'`scripts/bridge_detail10.py` exposes `apply(old_names)` for an independently opened frozen09. Pass exactly `bridge10-source-probe.json["exact_replace_names"]` after verifying source SHA; caller owns full before/after audit. It rejects missing names, non-parapet names, wrong list count and a second application while Bridge10 objects exist. It does not load source photographs or create new materials. This is an isolated candidate helper, not a production integration entry. Do not call it silently on another scene revision.','',
f"Helper SHA256 `{hashlib.sha256((R/'scripts/bridge_detail10.py').read_bytes()).hexdigest()}`.",'',
'Preserved negative evidence: original `Fallingwater_bridge_candidate10.blend` SHAaaf7c1abda92b54bd5dfd4790f40de593f3b5b8ba7c236c084aa0fc28bac49c1 and attempt02 check/readback files retain the44collinear cap triangles. The mesh-clean version changes only cap triangulation/one internal support point per new L. Attempt01 records the Blender5.2 triangulation return-type mismatch, fixed before any candidate save. The first unfiltered water-volume probe was interrupted and archived; spatial filtering reduced it to a local calculation without changing the answer.','',
'Independent source viewing and manifest proposal: `bridge10-reference-viewed.json`, `bridge10-reference-manifest-append.csv`, `bridge10-source-identity.json`. All three photos are reference-only, excluded from public packages and never textures. Central manifest untouched.','',
'Neat-freak reconciliation was limited to the owned bridge10 QA handoff/source notes; globalAGENTS/STATUS/production documentation remain parent-owned. No git commit was made (workspace root is not currently a Git repository).']
(Q/'bridge10-handoff.md').write_text('\n'.join(lines)+'\n',encoding='utf8')
(Q/'bridge10-doc-audit.json').write_text(json.dumps({'reviewed':{'bridge10-source-design.md':'Source identification and C dimensions remain current; authoritative achieved checks in handoff','bridge10-handoff.md':'Current mesh-clean artifact and incomplete water/visual acceptance explicit','bridge10-reference-manifest-append.csv':'24 original header columns; three rows; reference-only external rights retained','bridge10-water-spatial-mask.json':'Final exact core-volume clipping, camera suggestions, no water mutation'},'not_modified':['project/STATUS.md','AGENTS.md','project/reference_manifest.csv','project/scripts/site.py','project/scripts/build_scene.py','project/config.json'],'historical_failures_preserved':True},indent=2),encoding='utf8')
print('HANDOFF_WRITTEN',len(lines),'lines; candidate matches',hashlib.sha256(Path(c['candidate']).read_bytes()).hexdigest()==c['candidate_sha256'])
