"""Assemble source qualifications separately from mesh-probe results."""
from pathlib import Path
import csv,json,hashlib
Q=Path(__file__).resolve().parent;R=Q.parent
load=lambda p:json.loads(p.read_text(encoding='utf-8'))
mesh=load(Q/'dimensions10-actualmesh09-attempt02.json')
g=load(Q/'dimensions10-main10-cantilever-reading.json');g['view_status']='ACTUALLY_VIEWED';(Q/'dimensions10-main10-cantilever-reading.json').write_text(json.dumps(g,indent=2),encoding='utf-8')
witness=load(Q/'dimensions10-witness-annotations.json')
for item in witness:item['view_status']='ACTUALLY_VIEWED'
(Q/'dimensions10-witness-annotations.json').write_text(json.dumps(witness,indent=2),encoding='utf-8')
notes={
 'MAIN10_L2_WEST_TERRACE_X':('main05','28 ft 11 1/4 in','plan_projection','West terrace exterior parapet plane to dressing-room WEST stone face. Both source witnesses traced through actual physical outer faces; NOT a cantilever.','SOURCE_FACE_IDENTITY_CONFIRMED','FAIL',True),
 'MAIN10_L2_WEST_TERRACE_Y':('main05','17 ft 6 3/8 in','plan_span','North OUTER parapet face to south OUTER parapet face. The upper dimension tick is on the top outside outline; lower tick on the bottom outside outline. Neither is a centerline or inner finish face.','SOURCE_FACE_IDENTITY_CONFIRMED','FAIL',True),
 'MAIN10_L2_SOUTH_TERRACE_X':('main05','25 ft 5 1/4 in','plan_span','Opposite OUTER faces of the master-bedroom south terrace parapets. Both chain witnesses align with exterior lower corner outlines.','SOURCE_FACE_IDENTITY_CONFIRMED','FAIL',True),
 'MAIN10_L1_SERVICE_OUTER_X':('main04','10 ft 11 in','plan_span_diagnostic','West stone pier OUTSIDE face to kitchen stone WEST face, not room clear width. Frozen09 substitutes a continuous plaster wall for the source west pier; the chosen model wall is only a C correspondence.','SOURCE_TO_MODEL_IDENTITY_LIMIT','DIAGNOSTIC_NUMERIC_FAIL_NOT_QUALIFIED',False),
 'MAIN10_GRAPHICAL_L2_SOUTH_CANTILEVER':('main10',None,'cantilever','L2 south free exterior slab/parapet edge to the SOUTH face of the first full-height L1 stone pier in the west-looking section. Low window seat and glazing are not supports. This is graphical C, not an explicit cantilever dimension.','C_GRAPHICAL_SUPPORT_IDENTITY','GRAPHICAL_MISMATCH_SUPPORT_INTERFACE_UNRESOLVED',True),
 'GUEST10_THEATER_NORTH_BAY':('guest01','8 ft 1 7/8 in','openings','Whole slanted north masonry bay between diagonal-back stone and retained pier 2 inward reveal faces. This is an architectural framed opening, not one door leaf or post-frame net walking width. The mesh hits are those actual stone faces.','SOURCE_FACE_IDENTITY_CONFIRMED_BUT_LAYOUT_INCORRECT','FAIL',True),
 'GUEST10_THEATER_MIDDLE_BAY':('guest01','7 ft 1 1/8 in','openings','Whole slanted middle bay between retained piers 2 and 1. The source-derived axis misses pier1; the actual straight-wall glass cannot substitute for its absent source reveal.','SOURCE_REVEAL_ABSENT_ON_AXIS','GEOMETRY_CORRESPONDENCE_FAIL_NUMERIC_NOT_RUN',False),
}
sources={
 'main04':{'path':'../research/references/architecture/main-04-original.tif','sha256':'3db8199eeb84cd4226cfbae2ea9192880454c1012afa6e33bf84bae6449d8d56','source_authority':'HABS PA-5346 sheet4','url':'https://www.loc.gov/pictures/item/pa1690.sheet.00004a/'},
 'main05':{'path':'qa/dimension-sources08-main05-original.tif','sha256':'b8ecfc0128d9f5452e768032afd766976eb1e1b39cf85924a256e45baf50c891','source_authority':'HABS PA-5346 sheet5','url':'https://www.loc.gov/pictures/item/pa1690.sheet.00005a/'},
 'main10':{'path':'../research/references/architecture/main-10-original.tif','sha256':'db6591996c049961a50ba593c002dc394d5708f1c15c5935e1c3671aed1e2ac7','source_authority':'HABS PA-5346 sheet10','url':'https://www.loc.gov/pictures/item/pa1690.sheet.00010a/'},
 'guest01':{'path':'data/guest_refs/guest-01-original.tif','sha256':'70b5a22493be9568d04eafc94cb382fda17b1344f5a7c777973081df75f4a8b4','source_authority':'HABS PA-5346-A sheet1','url':'https://www.loc.gov/pictures/item/pa2187.sheet.00001a/'}}
rows=[]
for m in mesh['measurements']:
    sheet,label,category,semantics,identity,result,qualified=notes[m['id']]
    row={'id':m['id'],'source_id':sheet,'printed_label':label,'category':category,'source_value_evidence':'A printed label' if label else 'C graphical with A printed calibration','source_to_mesh_evidence':'C independently checked face identity, see qualification','view_status':'ACTUALLY_VIEWED','survey_absolute_accuracy_m':None,'survey_absolute_accuracy_status':'UNKNOWN','source_endpoint_semantics':semantics,'endpoint_identity_status':identity,'qualified_result':result,'qualifies_as_independent_measured_assertion':qualified,'measurement':m}
    if category=='cantilever':
        row['graphical_reading']=g;row['graphical_error_m']=m['actual_mesh_m']-g['graphical_target_m'];row['source_tolerance_rule']='Graphical reading interval only; NOT max(20mm,.5%) printed-dimension PASS';row['nominal_pass_eligible']=False
    else:row['source_tolerance_rule']='max(0.020m,0.005*printed_nominal_m)';row['nominal_pass_eligible']=qualified
    rows.append(row)
with (R/'dimensions.csv').open(encoding='utf-8-sig',newline='') as f:baseline=[{'id':r['component_id'],'label':r['original'],'category':r['feature_category'],'source_result':r['standard_result'],'scene_sha256':r['scene_sha256'],'remeasured_by_this_script':False} for r in csv.DictReader(f) if r['standard_result']=='PASS']
assert len(baseline)==15
out={'schema_version':1,'scope':'Independent source review + CPU4 read-only frozen09 evaluated mesh probes. Only project/qa/dimensions10* written; no central CSV/data/production/geometry modification.','review_status':'READY_FOR_COMBINED10_REMEASUREMENT_GEO02_NOT_PASS','sources':sources,'viewing':'Local original TIFF crops actually viewed. URLs are archive identifiers, not a fresh online verification.','source_crop_manifest':'qa/dimensions10-source-crops.json','source_witness_annotations':witness,'measurements':rows,'actualmesh_report':'qa/dimensions10-actualmesh09-attempt02.json','preserved_initial_attempt':'qa/dimensions10-actualmesh09-attempt01.json','support_interface':mesh['support_interface'],'frozen09_sha256':mesh['scene_sha256'],'frozen_scene_unchanged':mesh['scene_unchanged'],'rendered':False,'existing_qualified_09_anchors_not_rerun':baseline,'bridge_anchor':{'id':'SOURCE08_MAIN_BRIDGE_SOUTH_STONE_GAP','nominal_m':4.0386,'evidence_report':'qa/bridge10-handoff.md','actual_m_reported_by_owner':4.038599014,'remeasured_by_this_script':False,'independent_count':1,'multiple_ray_stations_are_repeats':True},'independence_accounting':{'baseline09_nominal_anchors':15,'bridge10_nominal_anchor':1,'new_qualified_nominal_measured_assertions':4,'new_qualified_nominal_PASS':0,'new_qualified_nominal_FAIL':4,'new_graphical_cantilever_assertions':1,'service_diagnostic_excluded_from_strict_count':1,'middle_opening_missing_endpoint_excluded_from_measured_count':1,'cross_candidate_nominal_measured_assertions_after_merge_and_retest':20,'cross_candidate_with_graphical_after_merge_and_retest':21,'same_combined_scene_verified_count':None,'standard_PASS_not_20':True,'dependence_note':'Same anchor across stations/frames/candidates counts once. Eight room-label source-precision-limit numeric PASS rows excluded. X/Y plan spans constrain different physical face pairs; the total chain sum is not added. Bridge and laundry repeat rays are not new anchors.'},'excluded_cantilever_substitutions':['main05 west terrace 28 ft11 1/4 in overall projection; lower service pier lies within its projection','main04 west terrace 16 ft2 3/8 in overall depth','main04 top11 ft8 in chain without verified support pair','main10 overall80 ft3 7/8 in and67 ft2 in are calibrations/overall spans, not cantilever lengths'],'retained_source_only_candidates_not_counted':[{'id':'MAIN05_WEST_CHAIN_33FT6_7_8','label':'33 ft 6 7/8 in','status':'SOURCE_READ_NOT_MEASURED','reason':'No extra value needed after three fully traced terrace spans; avoid speculative chimney projection station.'}],'next_run':'Run dimensions10-measure.py against parent-provided combination10 SHA, retaining original09 results. Central audit integration is parent-owned.'}
(Q/'dimensions10-source-review.json').write_text(json.dumps(out,indent=2,ensure_ascii=False),encoding='utf-8')
print(json.dumps(out['independence_accounting'],indent=2))
