from pathlib import Path
import json,hashlib
p=Path('project');q=p/'qa'
before=json.loads((q/'guest-dimensions-measured.json').read_text(encoding='utf-8'));after=json.loads((q/'guest-dimension-fixes-measured.json').read_text(encoding='utf-8'));fix=json.loads((q/'guest-dimension-fixes.json').read_text(encoding='utf-8'));stair=json.loads((q/'guest-dimension-fixes-clearance.json').read_text(encoding='utf-8'));doors=json.loads((q/'guest-dimension-fixes-doors.json').read_text(encoding='utf-8'));surfaces=json.loads((q/'guest-dimension-fixes-surfaces.json').read_text(encoding='utf-8'))
fix.update(status='PASS_FOR_10_CORRECTED_ANCHORS_AND_FOCUSED_REGRESSION',measurement_counts=after['counts'],measurement_report='qa/guest-dimension-fixes-measured.json',stair_regression={'status':stair['status'],'samples':len(stair['current_samples']),'minimum_clearance_m':stair['minimum_current_clearance_m'],'negative_control_failure_count':stair['old_slab_failure_count']},door_regression={'status':doors['status'],'doors':len(doors['doors']),'body_ray_samples':sum(len(x['samples']) for x in doors['doors']),'minimum_actual_height_m':min(x['actual_height_m'] for x in doors['doors'])},changed_room_structural_regression={'status':surfaces['status'],'samples':sum(len(r['samples']) for r in surfaces['rooms']),'movable_leaf_occupied_samples':sum(s['movable_door_leaf_at_sample'] for r in surfaces['rooms'] for s in r['samples']),'note':'All116 structural floor/ceiling probes pass; one boiler sample first hits an open doorleaf. That occupancy is explicitly retained, not reported as free walking volume. Door passage has separate body-ray test.'},fixed_scene_sha256=after['source_scene_sha256'],overlays=[o['path'] for o in after['overlays']],viewed=True,absolute_site_registration_unchanged=True)
fix['integration_requirements']=['Root must rebuild latest complete scene; working.blend isstill iteration03 and wasnot modified bythissubtask.','Rebuild furnishings fromupdated guest room census; bath/laundry/guest positions changed.','Re-run complete surface/navigation/terrain tests, particularly corrected westbasement extent and L2upperterrace camera view.','Keep5 unresolvedsourceendpoint dimensions NOT_RUN; sourcebounds/printedroomlabels do not authorize invented survey endpoints.','Connector canopy elevation remains visibly approximate; thisreport doesnot declareGEO-03 complete.']
(q/'guest-dimension-fixes.json').write_text(json.dumps(fix,ensure_ascii=False,indent=2),encoding='utf-8')
dp=p/'data/guest_house.json';d=json.loads(dp.read_text(encoding='utf-8'));d['dimension_fix_revision']='iteration04 guest corrections; 10 repaired anchors verified on actual evaluated module mesh; overall17PASS/0FAIL/5NOT_RUN; integrationpending'
d['dimension_mesh_qa']={'baseline':'qa/guest-dimensions-measured.json','corrected':'qa/guest-dimension-fixes-measured.json','counts':after['counts'],'scene_sha256':after['source_scene_sha256'],'method':'Actual evaluatedmesh rays/extrema, no reference-value substitution','scope':'guest module; full scene awaitingrebuild'}
dp.write_text(json.dumps(d,ensure_ascii=False,indent=2),encoding='utf-8')
lines=['# 客房尺寸修复及真实网格复验','', '**10 项修复全部通过；同一组 22 项锚点现为 17 PASS / 0 FAIL / 5 NOT_RUN。** 本报告只关闭明确测得的尺寸问题及专项回归，不代表完整模型或照片级验收完成。','', '修复前：`guest-dimensions-measured.md/json`，保留原始 7 PASS / 10 FAIL / 5 NOT_RUN 及原图叠合。修复后：`guest-dimension-fixes-measured.json`，独立模块检查点 `guest-dimension-fixes-module.blend`。没有覆盖整合工作场景。','',f"修复后场景 SHA-256：`{after['source_scene_sha256']}`。Blender 5.2.1、4 线程、无渲染。测量继续用同一套实际 evaluated mesh 射线/极值方法；容差保持 `max(20mm, 0.5%×原图长度)`。",'', '| 锚点 | 原图 m | 修复前 m | 修复后实测 m | 修复后偏差 mm | 结果 |','|---|---:|---:|---:|---:|---|']
old={r['id']:r for r in before['measurements']}
for r in after['measurements']:
 if old[r['id']]['status']=='FAIL':lines.append(f"| {r['id']} | {r['reference_m']:.6f} | {old[r['id']]['actual_mesh_measurement_m']:.6f} | {r['actual_mesh_measurement_m']:.6f} | {r['delta_m']*1000:+.4f} | {r['status']} |")
lines+=['','## 按源图协调相邻构件','', '- 客房：保留北侧石脊和东侧门的实际端点；浴室东隔墙向东 0.25540 m，卧房与浴室南侧墙共同向南 0.27456 m。同步浴室软木地面、客房/浴室/廊道/露台多边形及南侧柜位置。','- 锅炉房：保持南墙与西门原始端点，向北扩 0.22084 m、向东扩 0.06864 m；地板、屋面、空间记录随墙修正。入口凹口的精细源图形状仍属于未完成的形态匹配，未用本次净尺寸通过掩盖。','- 地下洗衣房/浴室：保持东側入口和服务楼梯，修正共用隔墙、浴室西墙、北侧围护。另从原图独立读出 18′9⅞″=5.737225 m 总宽链，约束西内面至东外面。地下西边界扩至图 x175.36863，顶板仅补现有首层之外的差集，避免同面重复。软木墙衬范围、门洞比例、房间多边形及楼板共同更新。','- 泳池：保留 9.1694×3.9624 m 内壳，外沿宽改为 9.617075 m；均匀外沿偏移 0.2238375 m。横向同宽属于原图形态支持的 C 级解释，未称另有宽度标注。','- 上层尖角露台：四片围墙从 L2 地面上 1.04 m 提至 2.159 m，最终墙顶相对客房地坪 4.511675 m。原图西立面 14′9⅝″墙顶与 7′8⅝″二层地坪明确区分。眼平视线现在受完整围墙遮挡，原先可越过矮墙的方向会被遮住；此为源图要求，不调整相机来掩盖。','', '## 实际回归结果','', f"- 服务楼梯：{len(stair['current_samples'])} 个踏步/平台/西返走道样本均通过，最低净高 {stair['minimum_current_clearance_m']:.3f} m；重新放回旧坏楼板可检测 {stair['old_slab_failure_count']} 个失败，负向回归有效。", '- 5 处受影响门洞：60 条真实穿墙厚度方向的身体射线通过，覆盖宽 0.48 m、四个身高截面。门顶 underside 实測最小 1.955 m、最大 2.075 m。仅表示这些门洞身体截面通畅，不等于全部导航录屏已完成。','- 五个改变的室内空间：116 个实际结构地板/顶面采样通过。锅炉房有 1 个全场景首先命中已打开门扇的采样；其占用被保存在报告中，结构测试只过滤可动门扇，不能把此点称为自由行走空间。门洞本身另经真实身体射线通过。','- 构建、保存和再次载入专项检查点均实际成功。Blender 尝试写入全局扩展缓存时出现权限提示；模块构建与测量均完成且进程退出码为 0，没有修改全局权限。','', '## 同坐标修复后叠合','', '灰色原图、红色实测网格边。保持修复前相同映射、范围与不确定性，没有逐物体拟合，两个 PNG 均已实际打开检查。具体映射、构件列表及投影边在修复后测量 JSON 中。','', '![修复后首层](D:/zx/test/project/qa/guest-dimension-fixes-plan-overlay.png)','', '![修复后西立面](D:/zx/test/project/qa/guest-dimension-fixes-west-overlay.png)','', '## 交接与边界','', '整合者应重建完整场景，再按新房间记录生成家具、相机与地形空域，并重验地下西扩区域和上层露台视线。`working.blend` 仍是旧迭代；本次 `.blend` 只有客房模块，不能用来替代全场景。','', '5 个端点语义未确定的剧场/服务翼锚点仍为 NOT_RUN；绝对客房高差仍为 C 级估计。本次尺寸通过不解决雨棚分段立面形态、原图中门窗细节、完整照片匹配、实际GUI漫游、4K与影片。','', '## 证据与复算入口','', '- `guest-dimension-fixes-measured.json`：22项原图/实测/差值/容差和真实对象端点。','- `guest-dimension-fixes-check.py`：仅新后台进程运行，构建客房模块、同锚点实际重测、楼梯负向回归、五门洞通行截面。','- `guest-dimension-fixes-clearance.json`、`guest-dimension-fixes-doors.json`、`guest-dimension-fixes-surfaces.json`：逐点碰撞对象和坐标。','- `guest-dimension-fixes-projection.json`：真实网格世界坐标边线，支持审计投影。','- `guest-dimension-fixes-before-guest_house.*`：变更前模块/数据备份。`guest-dimension-fixes-apply.py` 是历史一次性变更记录，不可对已修文件重复运行。','', '本阶段按 neat-freak 核对了根约定、README、STATUS 与客房 QA 文档。项目级规则和交付状态由整合者维护，不追加流水记录或覆写其他代理文件；具体几何证据集中在本报告，并已通知家具/场地/整合任务。','']
(q/'guest-dimension-fixes.md').write_text('\n'.join(lines),encoding='utf-8')
print('FINAL',after['counts'],'surfaces',fix['changed_room_structural_regression'])
