from pathlib import Path
import json
p=Path('project/qa');r=json.loads((p/'guest-dimensions-measured.json').read_text(encoding='utf-8'))
for o in r['overlays']:o['view_status']='VIEWED';o['visual_review']='Opened and inspected actual source/mesh overlay; discrepancies remain visible, no per-object fitting.'
r['high_priority_findings']=[{'priority':'P1','ids':['GUEST_TOP_STONE'],'finding':'Upper pointed service-terrace stone enclosure top is 1.1189996 m below the printed 4.511675 m datum. West overlay shows corresponding stepped-height mismatch.','next_action':'Confirm printed datum refers to complete stone enclosure then increase associated terrace wall height; preserve floor datum and adjacency.'},{'priority':'P1','ids':['GUEST_GUEST_ROOM_LENGTH','GUEST_GUEST_ROOM_DEPTH','GUEST_BOILER_DIM_1','GUEST_BOILER_DIM_2','GUEST_LAUNDRY_LENGTH','GUEST_LAUNDRY_DEPTH','GUEST_BASE_BATH_WIDTH'],'finding':'Face-to-face dimensions differ by 69-275 mm. Source room labels are A evidence, finished-face endpoint interpretation is C.','next_action':'Reinspect original face/wall centerlines, coordinate neighboring partitions, openings and room census; avoid stretching one object independently.'},{'priority':'P2','ids':['GUEST_POOL_OUTER_WIDTH'],'finding':'Clear basin passes, exterior coping horizontal dimension is 157.675 mm short.','next_action':'Preserve clear shell, resolve actual outer coping boundary from source and expand ring only if confirmed.'},{'priority':'P2','ids':['GUEST_BASE_BATH_LENGTH'],'finding':'21.959 mm long versus strict 20 mm tolerance, marginal against source tracing uncertainty.','next_action':'Resolve jointly with basement partition correction; do not treat near-threshold scan uncertainty as precise proof.'}]
(p/'guest-dimensions-measured.json').write_text(json.dumps(r,ensure_ascii=False,indent=2),encoding='utf-8')
lines=['# 客房独立网格尺寸核验 — iteration03 修复前','', '**结果：7 PASS / 10 FAIL / 5 NOT_RUN。** 这是已保存场景的真实网格测量，不能作为项目验收通过。此次仅新增证据，未覆盖 working.blend。','',f"场景：`{r['source_scene']}`；修改时间 `{r['source_scene_mtime']}`；SHA-256 `{r['source_scene_sha256']}`。Blender 5.2.1 后台只读、4 线程，无渲染。",'', '测量使用 evaluated mesh 的世界坐标顶点、实际表面射线与几何极值。参考 JSON 的 `model_value_m` 没有作为测量结果使用。泳池边沿集合只包含数字编号 coping 环，已排除同前缀的上行楼梯扶手。','', '容差严格采用 QA GEO-02：`max(0.020 m, 0.005 × 参考尺寸)`。原图读数不确定性另列，不扩大通过门槛。A 表示原图标注，C 表示净面/构件归属解释；二者与是否实际测量分开。','', '| 锚点 | 原图 | 参考 m | 实测 m | 差值 mm | 容差 mm | 结果 |','|---|---|---:|---:|---:|---:|---|']
for x in r['measurements']:
 actual='—' if x['actual_mesh_measurement_m'] is None else f"{x['actual_mesh_measurement_m']:.6f}"
 delta='—' if x['delta_m'] is None else f"{x['delta_m']*1000:+.3f}"
 lines.append(f"| {x['id']} | {x['original']} | {x['reference_m']:.6f} | {actual} | {delta} | {x['tolerance_m']*1000:.1f} | {x['status']} |")
lines+=['','## 高优先级复核与修正建议','', '1. 上层尖角服务露台的石墙顶实测 3.392675 m，原图标高 4.511675 m，低 1.119 m。西立面叠合可直接辨认高度差，须修正关联围墙而非修改标注。','2. 客房净尺寸 +255 / −275 mm；锅炉房 −221 / −69 mm；洗衣房 −163 / −231 mm；地下浴室宽 −173 mm。修正前须逐项确认净面定义，连同相邻墙、门、房间多边形一并协调。','3. 泳池内壳两净尺寸通过，外沿宽短 158 mm，应先确认外侧界线后只调整外环。地下浴室长度 +22 mm 属边界偏差，不能忽略扫描不确定性。','', '## 原图与实际网格叠合','', '红线为已保存场景的 evaluated mesh 真正边线，灰色为 HABS 原图，蓝色为实测线段或标高差。两图均为透视遮挡未消除的正交投影，未逐物体拟合。全量构件名和投影线存在配套 JSON，可复算。','', '![首层叠合](D:/zx/test/project/qa/guest-dimensions-measured-plan-overlay.png)','', '平面：原图统一 1024×790 坐标，`px=325+(X−3.4)/0.05256`，`py=422−(Y−37.1)/0.05272`。含首层楼板/墙/窗、泳池、两组服务梯；不含二层与地下室围护、屋面、家具、装饰砌石。图上约 1 px 追踪不确定性等于 53 mm。','', '![西立面叠合](D:/zx/test/project/qa/guest-dimensions-measured-west-overlay.png)','', '西立面水平尺度独立采用原图 66′2⅜″=20.177125m、见证端点 px221.5→606.0；垂直采用 SECOND LEVEL 7′8⅝″=2.352675m、py243→199。映射 `px=577−(Y−37.1)/0.052476268`，`py=243−(Z−8.3999996)/0.053469886`。服务东南角定位 ±2px，尺寸见证端点 ±1px；没有用石墙顶目标单独拟合。包含西侧服务外墙、上层露台、选定楼板屋面和连接雨棚，完整列表见 JSON。','', '两张叠合均已实际打开检查。连接雨棚仍存在源图立面形状偏差，此次尺寸锚点审计未判其通过。','', '## 逐项对象与端点证据','']
for x in r['measurements']:
 lines += [f"### {x['id']} — {x['status']}",'',f"来源：{x['source']}；标注 {x['original']}；读数不确定性 ±{x['source_reading_uncertainty_m']:.4f} m。",'',x['method'],'',x['evidence']+'.','']
 if x['endpoints']:
  for k,pt in enumerate(x['endpoints'],1):lines.append(f"- 端点 {k}：`{pt['object']}`，世界坐标 `{pt['point_m']}` m。")
  lines+=['']
lines+=['## 限制','', '5 个 NOT_RUN 均未找到可靠的原图见证点到当前网格端点的对应：剧场两个斜向名义尺寸、服务翼总 Y 尺寸、剧场北侧斜墙投影升高及东侧局部段。不能用整体包围盒代替这些尺寸。','', '绝对客房标高 8.4 m 仍是跨楼注册 C 级估计（7.4–9.4 m），本报告的局部标高通过不证明绝对位置准确。内部净面不含装饰石块突出，遇到实际软木墙衬则包含墙衬。后续修复与重测须另写 `guest-dimension-fixes*`，保留此修复前证据。','']
(p/'guest-dimensions-measured.md').write_text('\n'.join(lines),encoding='utf-8')
print('REPORT COMPLETE',r['counts'])
