"""Independently reproduce the main-house generated data after build09."""
import hashlib
import json
import sys
from pathlib import Path
root=Path(__file__).resolve().parents[1]
sys.path.insert(0,str(root/'scripts'))
import main_house
record=json.loads((root/'qa/integration09-freeze.json').read_text(encoding='utf-8'))
assert hashlib.sha256((root/'scripts/main_house.py').read_bytes()).hexdigest()==record['inputs']['scripts\\main_house.py']
actual=(root/'data/main_house.json').read_bytes()
generated=main_house.export_data()
payload=json.dumps(generated,ensure_ascii=False,indent=2).replace('\n','\r\n').encode('utf-8')
same=actual==payload
differences=[]
def diff(a,b,path=''):
    if type(a) is not type(b):
        differences.append({'path':path,'saved':a,'fresh':b})
    elif isinstance(a,dict):
        for k in sorted(set(a)|set(b)):
            if k not in a or k not in b:
                differences.append({'path':path+'/'+k,'saved':a.get(k),'fresh':b.get(k)})
            else: diff(a[k],b[k],path+'/'+k)
    elif isinstance(a,list):
        if len(a)!=len(b):differences.append({'path':path,'saved_count':len(a),'fresh_count':len(b)})
        else:
            for i,(av,bv) in enumerate(zip(a,b)):diff(av,bv,path+'/'+str(i))
    elif a!=b: differences.append({'path':path,'saved':a,'fresh':b})
diff(json.loads(actual),json.loads(payload))
result={'status':'PASS' if same else 'FAIL','actual_sha256':hashlib.sha256(actual).hexdigest(),
        'independent_source_export_sha256':hashlib.sha256(payload).hexdigest(),
        'before_build_sha256':record['inputs']['data\\main_house.json'],
        'method':'Fresh Blender process imports unchanged frozen main_house.py and calls export_data without a path; exact generated UTF-8/Windows-CRLF bytes compared to the build output. JSON values independently compared after serialization. No scene or data saved.',
        'classification':'data/main_house.json is generated by main_house.build(), not an immutable input to it',
        'differences':differences}
(root/'qa/integration09-generated-data-check.json').write_text(json.dumps(result,indent=2),encoding='utf-8')
print(json.dumps(result,indent=2))
assert same
